### ISSUE TITLE
library is broken

### ISSUE THREAD

**Issue by nashid** [daveshap/VDBLITE#8]
Library does not load. Exception details below:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lib/python3.9/site-packages/vdblite/__init__.py", line 41
    result.append self.data[idx]
                  ^
SyntaxError: invalid syntax
```

**Comment by daveshap** [comment]
Index-based search is not functional yet. Check release notes.
