### ISSUE TITLE
Cant load library after pip install

### ISSUE THREAD

**Issue by nashid** [daveshap/VDBLITE#9]
I know there was a confusion in my previous post.

Please note library is completely broken. Basically I did `pip install` and then attempted to load the library. 

At that point I get the following exception trace:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lib/python3.9/site-packages/vdblite/__init__.py", line 41
    result.append self.data[idx]
                  ^
SyntaxError: invalid syntax
```

**Comment by daveshap** [comment]
I see. I fixed it. Please run `pip install vdblite --upgrade` to go to version 0.1.3 https://pypi.org/manage/project/vdblite/release/0.1.3/

**Comment by nashid** [comment]
great 👍
